# Generated by Django 4.0.3 on 2022-03-24 14:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting_name', models.CharField(max_length=20)),
                ('number_of_voters', models.IntegerField(default=0)),
                ('list_of_candidates', models.JSONField()),
                ('date_of_start', models.DateTimeField()),
                ('date_of_end', models.DateTimeField()),
                ('end_of_elections', models.DateTimeField()),
                ('distribution_way', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsibleRepresentative',
            fields=[
                ('mail', models.CharField(max_length=20, unique=True)),
                ('rr_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('elections_name', models.CharField(max_length=20)),
                ('voter_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('new_field_for_delete', models.CharField(max_length=50, null=True)),
                ('rr_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.blank')),
            ],
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('bulletin_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('downloaded', models.BooleanField(default=False)),
                ('voter_choise', models.CharField(default=None, max_length=50, null=True)),
                ('elections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.blank')),
                ('voter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vote.voter')),
            ],
        ),
    ]
