# Generated by Django 4.0.3 on 2022-03-22 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting_name', models.CharField(max_length=20)),
                ('number_of_voters', models.IntegerField(default=0)),
                ('number_of_candidates', models.IntegerField(default=0)),
                ('date_of_start', models.DateTimeField()),
                ('date_of_end', models.DateTimeField()),
                ('end_of_elections', models.DateTimeField()),
                ('distribution_way', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsibleRepresentative',
            fields=[
                ('mail', models.CharField(max_length=20, unique=True)),
                ('rr_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elections_name', models.CharField(max_length=20)),
                ('voter_uuid', models.CharField(max_length=20, unique=True)),
                ('rr_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.responsiblerepresentative')),
            ],
        ),
    ]
