# Generated by Django 4.0.3 on 2022-03-22 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='rr_login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.blank'),
        ),
    ]
