# Generated by Django 4.0.3 on 2022-03-24 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='new_field_for_delete',
        ),
    ]
